### ISSUE TITLE
登录框

### ISSUE THREAD

**Issue by dengxiaodan** [Playfresh/web-redesign#8]
1.错误提示字颜色不对，应为＃ FF5C5D
2.按钮会出现黄色的情况
3.按钮上的登录俩字去掉内阴影效果
4.框外部的阴影颜色太脏，可尝试＃C7A82B看看
![d06be228-631b-475b-8f6c-e780bf39a607](https://cloud.githubusercontent.com/assets/16201057/11707045/fec06070-9f39-11e5-84f2-8820404ff0f5.jpg)

**Comment by EthanWu** [comment]
已修复。
